deployments: youtube docker-compose

diff --git a/bin/initdb b/bin/initdb
--- a/bin/initdb
+++ b/bin/initdb
@@ -2,23 +2,21 @@
 
 basename=`dirname $0`
 
-if ! mysql -u root -p${DATABASE_PASSWORD} -e "" ; then
-  echo
-  echo "Can't configure the database:-(  Bailing..."
-  exit 1
-fi
+until mysql -u root -p${DATABASE_PASSWORD} -h database -e "" ; do
+  echo "Can't configure the database:-(  waiting..."
+done
 
-if ! mysql -u root -p${DATABASE_PASSWORD} ${DATABASE_NAME} -e "select count(*) from SequelizeMeta;"; then
+if ! mysql -u root -p${DATABASE_PASSWORD} -h database ${DATABASE_NAME} -e "select count(*) from SequelizeMeta;"; then
   echo "Creating database and API service user."
   echo
-  mysql -u root -p${DATABASE_PASSWORD} << EOF
+  mysql -u root -p${DATABASE_PASSWORD} -h database << EOF
 CREATE DATABASE ${DATABASE_NAME};
 CREATE USER '${DATABASE_USER}' IDENTIFIED BY '${DATABASE_PASSWORD}';
 GRANT ALL on ${DATABASE_NAME}.* to ${DATABASE_USER};
 EOF
 
   # Load initial set of tables
-  mysql -u root -p${DATABASE_PASSWORD} ${DATABASE_NAME} < ${basename}/../packages/backend-core/seed/initial-database.sql
+  mysql -u root -p${DATABASE_PASSWORD} -h database ${DATABASE_NAME} < ${basename}/../packages/backend-core/seed/initial-database.sql
   ${basename}/osmod migrate
 
   # Add a service user that can talk to the Perspective API:
